import type { Metadata } from 'next';
import './globals.css';
import { arimo } from './fonts';
import Header from './components/header';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={arimo.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
